### ISSUE TITLE
passing time as an argument

### ISSUE THREAD

**Issue by asutosh97** [jjsquillante/animated-octo-dollop#1]
passing the time as an argument to the countDownClock function would give it more flexibility. Can I contribute this feature?

PS:- I am also a student of Gordon, learning PracticalJS and new to open-source.

**Comment by jjsquillante** [comment]
@asutosh97  sure - sounds good!

**Comment by asutosh97** [comment]
@jjsquillante I have made a pull request, let me know if its good enough or needs some refining.
